const API='https://api.tarkov.dev/graphql';
const STORE='tarkov-key-guide-owned-v1';
const query=`query { items(types:[keys],lang:en){id name shortName normalizedName iconLink wikiLink properties{... on ItemPropertiesKey{uses}}} }`;
let items=[];
const el=id=>document.getElementById(id);
function getOwned(){try{return JSON.parse(localStorage.getItem(STORE))||{}}catch{return {}}}
function setOwned(obj){localStorage.setItem(STORE,JSON.stringify(obj))}
function mapFor(name){const n=name.toLowerCase();if(/lab|keycard|access card/.test(n))return 'Labs / Keycards';if(/dorm|customs|tarcone|factory exit|portable cabin|machinery|director|gas station|checkpoint/.test(n))return 'Customs / Factory';if(/shoreline|resort|sanatorium|cottage|weather station/.test(n))return 'Shoreline';if(/reserve|rb-|bunker/.test(n))return 'Reserve';if(/interchange|ultra|kiba|emercom|oli|goshan|idea/.test(n))return 'Interchange';if(/streets|concordia|beluga|primorsky|chekannaya|pinewood|lexos/.test(n))return 'Streets';if(/lighthouse|water treatment|merin|conference/.test(n))return 'Lighthouse';if(/woods|sawmill|zb-014|zb-016/.test(n))return 'Woods';return '기타 / 맵 확인 필요'}
function render(){const search=el('search').value.toLowerCase().trim(),map=el('map').value,filter=el('filter').value,owned=getOwned();const shown=items.filter(x=>(map==='all'||x.map===map)&&(!search||(x.name+' '+x.shortName+' '+x.id).toLowerCase().includes(search))&&(filter==='all'||(filter==='owned'?!!owned[x.id]:!owned[x.id])));el('status').textContent=`전체 ${items.length}개 · 현재 ${shown.length}개 표시 · 보유 ${Object.keys(owned).filter(k=>owned[k]).length}개`;const frag=document.createDocumentFragment();for(const x of shown){const card=document.createElement('article');card.className='card';const img=document.createElement('img');img.alt='';img.loading='lazy';if(x.iconLink)img.src=x.iconLink;card.append(img);const h=document.createElement('h2');h.textContent=x.name;card.append(h);const meta=document.createElement('small');meta.textContent=x.map;card.append(meta);if(x.wikiLink){const a=document.createElement('a');a.href=x.wikiLink;a.target='_blank';a.rel='noopener noreferrer';a.textContent='위키에서 상세 정보 보기 ↗';card.append(a)}const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.checked=!!owned[x.id];check.addEventListener('change',()=>{const data=getOwned();if(check.checked)data[x.id]=true;else delete data[x.id];setOwned(data);render()});label.append(check,document.createTextNode('보유 중'));card.append(label);frag.append(card)}el('cards').replaceChildren(frag)}
async function load(){try{const res=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query})});if(!res.ok)throw Error('HTTP '+res.status);const data=await res.json();if(data.errors)throw Error(data.errors[0].message);if(!Array.isArray(data.data?.items))throw Error('데이터 형식 오류');items=data.data.items.map(x=>({...x,map:mapFor(x.name)})).sort((a,b)=>a.name.localeCompare(b.name));const maps=[...new Set(items.map(x=>x.map))].sort();for(const m of maps){const o=document.createElement('option');o.value=m;o.textContent=m;el('map').append(o)}render()}catch(e){el('status').textContent='데이터를 불러오지 못했습니다: '+e.message+' · 인터넷 연결 또는 API 상태를 확인해주세요.'}}
for(const id of ['search','map','filter'])el(id).addEventListener(id==='search'?'input':'change',render);
el('export').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({version:1,owned:getOwned()},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='tarkov-key-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});
el('import').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{const d=JSON.parse(await f.text());if(d.version!==1||!d.owned||typeof d.owned!=='object'||Array.isArray(d.owned))throw Error('지원하지 않는 백업 파일');const clean={};for(const [k,v] of Object.entries(d.owned)){if(typeof k==='string'&&k.length<100&&v===true)clean[k]=true}setOwned(clean);render();alert('보유 현황을 가져왔습니다.')}catch(err){alert('가져오기 실패: '+err.message)}e.target.value=''});
load();
